const SET_PRODUCTS = 'SET_PRODUCTS'
const STORE_PRODUCT_SAGA = 'STORE_PRODUCT_SAGA'
const SEARCH_PRODUCT_SAGA = 'SEARCH_PRODUCT_SAGA'
const CREATE_PRODUCT_SAGA = 'CREATE_PRODUCT_SAGA'
const UPDATE_PRODUCT_SAGA = 'UPDATE_PRODUCT_SAGA'
const DELETE_PRODUCT_SAGA = 'DELETE_PRODUCT_SAGA'

export { SET_PRODUCTS, CREATE_PRODUCT_SAGA, UPDATE_PRODUCT_SAGA, DELETE_PRODUCT_SAGA, STORE_PRODUCT_SAGA, SEARCH_PRODUCT_SAGA }