const STORE_USER = 'STORE_USER'
const STORE_USER_SAGA = 'STORE_USER_SAGA'
const TOKEN_USER_SAGA = 'TOKEN_USER_SAGA'
const LOGIN_GOOGLE_SAGA = 'LOGIN_GOOGLE_SAGA'
const LOGIN_ADMIN_SAGA = 'LOGIN_ADMIN_SAGA'

export { STORE_USER, STORE_USER_SAGA, TOKEN_USER_SAGA, LOGIN_GOOGLE_SAGA, LOGIN_ADMIN_SAGA }